driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

verifier:
  name: pester

platforms:
  - name: windows-2008r2-chef11.18.6
    driver_config:
      box: chef/windows-server-2008r2-standard
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: windows-2008r2-chef12
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2-chef11.18.6
    driver_config:
      box: chef/windows-server-2012r2-standard
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: windows-2012r2-chef12
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: tasks
    run_list:
      - recipe[windows::default]
      - recipe[test::tasks]
  - name: path
    run_list:
      - recipe[windows::default]
      - recipe[test::path]
  - name: certificate
    run_list:
      - recipe[windows::default]
      - recipe[test::certificate]
  - name: package
    run_list:
      - recipe[windows::default]
      - recipe[test::package]
  - name: feature
    run_list:
      - recipe[windows::default]
      - recipe[test::feature]
  - name: http_acl
    run_list:
      - recipe[windows::default]
      - recipe[test::http_acl]

  - name: font
    run_list:
      - recipe[windows::default]
      - recipe[test::font]
