---
driver:
  forward_agent: yes
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
  box: windows-8.1

transport:
  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: windows-8.1-chef11
    provisioner:
      require_chef_omnibus: 11.16.4
  - name: windows-8.1-chef12
    provisioner:
      require_chef_omnibus: 12.0.0

suites:
  - name: default
    run_list:
      - recipe[windows::default]
      - recipe[path_test::default]

