# rubocop todo

# These were backported from chef/chef and since we'll probably backport another fix later
# I want to be able to diff the code easily
AllCops:
  Exclude:
    - 'libraries/backported_task_provider.rb'
    - 'libraries/backported_task_resource.rb'

Lint/HandleExceptions:
  Exclude:
    - 'libraries/registry_helper.rb'
    - 'libraries/windows_helper.rb'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'libraries/registry_helper.rb'

Lint/UselessAssignment:
  Exclude:
    - 'libraries/registry_helper.rb'

Metrics/BlockNesting:
  Max: 5

Style/AccessorMethodName:
  Exclude:
    - 'libraries/matchers.rb'
    - 'libraries/version.rb'

Style/ClassVars:
  Exclude:
    - 'libraries/registry_helper.rb'

Style/GuardClause:
  Exclude:
    - 'libraries/registry_helper.rb'
    - 'libraries/windows_privileged.rb'

Style/IfInsideElse:
  Exclude:
    - 'libraries/powershell_helper.rb'

Style/RegexpLiteral:
  Exclude:
    - 'resources/task.rb'
