AllCops:
  Exclude:
    - vendor/**/*
    - Guardfile

AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FileName:
  Enabled: false
Style/StringLiterals:
  Enabled: false

# todo: resolve these issues:

Style/RegexpLiteral:
  Enabled: false
Style/GuardClause:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/RescueException:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Style/MethodName:
  Enabled: false
Style/VariableName:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/VariableName:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Style/Alias:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
